### PR TITLE
Inky update

### PR DESCRIPTION
**Pull request by userhas404d**
Hey @DurandA thanks for this awesome project! 

This PR is my attempt at updating things to use pimoroni's new [inky](https://github.com/pimoroni/inky) library. I used [black](https://github.com/psf/black) to format as I went so that's part of why this PR is touching so much. 

I don't have a waveshare so not sure if this breaks things for that implementation.

### CODE REVIEW

**Comment by DurandA** [comment]
Hi @userhas404d and thanks for the contribution!

My e-ink display is still in my office which is closed right now. I will merge your changes once I am able to test it.

**Review by DurandA — CHANGES_REQUESTED** [review]
Please use single quotes as it was originally. This is mostly a personal preference and recent Python documentation tends to use single quotes.

**Comment by DurandA** [comment]
Hi @userhas404d! I was finally able to retrieve my e-ink module. Unfortunately, the new `inky` module does not seem to work with the [Waveshare HAT](https://www.waveshare.com/product/displays/e-paper/epaper-3/2.13inch-e-paper-hat-b.htm) by just adjusting the pins.

I will investigate on this issue before merging your PR.

**Comment by DurandA** [comment]
Here is what Pimoroni wrote on the [Inky pHAT product page](https://shop.pimoroni.com/products/inky-phat?variant=12549254938707):

> Note that we've completely re-written the Python library (as of October 2018) to be compatible with both Inky pHAT and the larger Inky wHAT displays. This new Inky Python library drops support for the original (V1) Inky pHAT, but you can still use the original Inky pHAT Python library if you have one of these original boards.

Unfortunately, the schematic of these modules is not available so I am not sure if they use a different display.

**Comment by userhas404d** [comment]
>Unfortunately, the schematic of these modules is not available so I am not sure if they use a different display.

:,( I read through your issue on the upstream library and I understood some of those words.. Worst case scenario recommend maintaining this and the "legacy" codebase on separate branches. 110% your call though.

**Comment by DurandA** [comment]
Hi @userhas404d!

I packaged this project so it can be installed via pip. This is still in the `develop` branch. You can use `pip install -e` to install local project in editable mode to try it out. Would you mind creating a new PR to this branch with your changes?

If most of the code of cli.py can be shared between the `inky` and `inkyphat` versions, we can try to pass a flag to use the legacy `inkyphat`. Otherwise, we can also use two different files in a `cli` module which is more convenient than managing two branches.

Let me know what you think.

**Comment by DurandA** [comment]
I imagine we could do something along the lines of:
```
from inkyphat import set_image, show
class InkyPHAT():
    def __init__(*args):
        pass
    set_image = set_image
    show = show
```
Then we can use it as if it was the newer library. Since all the drawing is done as Pillow image manipulation, we in fact don't need any other functions besides `set_image()` and `show()`.

**Comment by DurandA** [comment]
I repackaged everything in the `inky` branch. It should now be much easier to integrate your changes. :relaxed:

**Comment by DurandA** [comment]
Hi @userhas404d! Sorry I kind of forgot about this project for a while.

I updated the software and it now uses the `inky` lib and is more flexible with regard to drivers. Let me know if you have any suggestion.

**Pull request closed without merging**
